{
 "title": "FlinkAutoScaler",
 "description": "Flink AutoScaler Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# of Running Jobs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_numRunningJobs"
    }
   ]
  },
  {
   "title": "# of TaskManagers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers"
    }
   ]
  },
  {
   "title": "Job-Uptime",
   "type": "graph",
   "description": "Job-Uptime",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "flink_jobmanager_job_uptime", "legendFormat": "{{host}}_{{job_name}}" }
   ]
  },
  {
   "title": "Parallelism",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(flink_jobmanager_taskSlotsTotal) - (flink_jobmanager_taskSlotsAvailable)",
     "legendFormat": "Used TaskSlots"
    }
   ]
  },
  {
   "title": "Taskslots total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsTotal"
    }
   ]
  },
  {
   "title": "Taskslots available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsAvailable"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Throughput",
   "type": "graph",
   "description": "Number of Records out per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_numRecordsOutPerSecond{task_name=\"Source:_iSource\"})",
     "legendFormat": "Source"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_numRecordsOutPerSecond{task_name=\"iMap\"})",
     "legendFormat": "MAP"
    }
   ]
  },
  {
   "title": "RecordsOutPerSecond (MAP Replicas)(task-level)",
   "type": "graph",
   "description": "RecordsOutPerSecond (MAP Replicas)",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_numRecordsOutPerSecond{task_name=\"iMap\"})",
     "legendFormat": "Map"
    }
   ]
  },
  {
   "title": "RecordsOutPerSecond (MAP Replicas)(Subtask-level)",
   "type": "graph",
   "description": "RecordsOutPerSecond (MAP Replicas)",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (subtask_index) (flink_taskmanager_job_task_operator_numRecordsOutPerSecond{task_name=\"iMap\"})",
     "legendFormat": "MAP_{{subtask_index}}"
    }
   ]
  },
  { "title": "BackPressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Back Pressure (Source)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (task_name) (flink_taskmanager_job_task_isBackPressured{task_name=\"Source:_iSource\"})",
     "legendFormat": "Source"
    }
   ]
  },
  {
   "title": "Back Pressure (Map Replicas)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (subtask_index) (flink_taskmanager_job_task_isBackPressured{task_name=\"iMap\"})",
     "legendFormat": "MAP_{{subtask_index}}"
    }
   ]
  },
  {
   "title": "CPU & Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "JobManager Memory Used",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Direct_MemoryUsed",
       "legendFormat": "JobManager"
      }
     ]
    },
    {
     "title": "TaskManager Memory Used",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Direct_MemoryUsed",
       "legendFormat": "TM on:{{instance}}"
      }
     ]
    },
    {
     "title": "JobManager CPU Load",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_CPU_Load",
       "legendFormat": "JobManager"
      }
     ]
    },
    {
     "title": "TaskManager CPU Load",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_CPU_Load",
       "legendFormat": "TM on:{{instance}}"
      }
     ]
    },
    {
     "title": "JobManager Heap Memory",
     "type": "graph",
     "description": "JVM Memory Heap Used vs JVM Memory Heap Max",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used",
       "legendFormat": "Used"
      },
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Max",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "TaskManager Heap Memory",
     "type": "graph",
     "description": "JVM Memory Heap Used vs JVM Memory Heap Max",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_Status_JVM_Memory_Heap_Used)",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(flink_taskmanager_Status_JVM_Memory_Heap_Max)",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "JobManager Buffers",
     "type": "graph",
     "description": "JVM Memory Direct Buffers vs JVM Memory Total Capacity of Direct Buffers",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Direct_Count",
       "legendFormat": "Used "
      },
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Direct_TotalCapacity",
       "legendFormat": "Available "
      }
     ]
    },
    {
     "title": "Taskmanager Buffers",
     "type": "graph",
     "description": "JVM Memory Direct Buffers vs JVM Memory Total Capacity of Direct Buffers",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 32 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_Status_JVM_Memory_Direct_Count)",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(flink_taskmanager_Status_JVM_Memory_Direct_TotalCapacity)",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "JobManager CPU Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "100*flink_jobmanager_Status_JVM_CPU_Load",
       "legendFormat": "JobManager"
      }
     ]
    },
    {
     "title": "TaskManager CPU Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 39 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "100 * flink_taskmanager_Status_JVM_CPU_Load",
       "legendFormat": "TM on:{{instance}}"
      }
     ]
    },
    {
     "title": "JobManager overall CPU usage",
     "type": "graph",
     "description": "JobManager CPU USE",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_System_CPU_Usage",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "TaskManager overall CPU Usage",
     "type": "graph",
     "description": "TaskManager CPU USE",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 39 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_System_CPU_Usage",
       "legendFormat": "{{host}}_{{tm_id}}"
      }
     ]
    },
    {
     "title": "Taskmanager every CPUs utilization",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_System_CPU_UsageCPU0",
       "legendFormat": "{{host}}_CPU#0_{{tm_id}}_{{instance}}"
      },
      {
       "expr": "flink_taskmanager_System_CPU_UsageCPU1",
       "legendFormat": "{{host}}_CPU#1_{{tm_id}}_{{instance}}"
      },
      {
       "expr": "flink_taskmanager_System_CPU_UsageCPU2",
       "legendFormat": "{{host}}_CPU#2_{{tm_id}}_{{instance}}"
      },
      {
       "expr": "flink_taskmanager_System_CPU_UsageCPU3",
       "legendFormat": "{{host}}_CPU#3_{{tm_id}}_{{instance}}"
      },
      {
       "expr": "flink_taskmanager_System_CPU_UsageCPU4",
       "legendFormat": "{{host}}_CPU#4_{{tm_id}}_{{instance}}"
      },
      {
       "expr": "flink_taskmanager_System_CPU_UsageCPU5",
       "legendFormat": "{{host}}_CPU#5_{{tm_id}}_{{instance}}"
      },
      {
       "expr": "flink_taskmanager_System_CPU_UsageCPU6",
       "legendFormat": "{{host}}_CPU#6_{{tm_id}}_{{instance}}"
      },
      {
       "expr": "flink_taskmanager_System_CPU_UsageCPU7",
       "legendFormat": "{{host}}_CPU#7_{{tm_id}}_{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Source to Sink Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(flink_taskmanager_job_latency_source_id_operator_id_operator_subtask_index_latency{job_name=\"UseCase1WithFibo\"})",
     "legendFormat": "Maximum Latency"
    },
    {
     "expr": "min(flink_taskmanager_job_latency_source_id_operator_id_operator_subtask_index_latency{job_name=\"UseCase1WithFibo\"})",
     "legendFormat": "Minimum Latency"
    },
    {
     "expr": "avg(flink_taskmanager_job_latency_source_id_operator_id_operator_subtask_index_latency{job_name=\"UseCase1WithFibo\"})",
     "legendFormat": "Average Latency"
    }
   ]
  },
  {
   "title": "Live Thread count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 23 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Threads_Count{job=\"flink\"}",
     "legendFormat": "JM on:{{instance}} "
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Threads_Count{job=\"flink\"}",
     "legendFormat": "TM on:{{instance}} "
    }
   ]
  }
 ]
}