apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini
  namespace: default
data:
  grafana.ini: |
    auth:
      disable_login_form: true
    auth.anonymous:
      enabled: true
      org_role: Editor
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: default
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "isDefault": "true",
                "url": "http://prometheus-service.default.svc:9090",
                "version": 1
            }
        ]
    }
